repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0  # Match with setup.cfg
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Match with setup.cfg
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Match with setup.cfg
    hooks:
      - id: mypy
